Repository paketo-buildpacks/go-dist, pull requests merged in 2022-03, with the labels that each got.

#370 Remove deprecated buildpack.yml features
  README.md
  build.go
  build_test.go
  buildpack_yaml_parser.go
  buildpack_yaml_parser_test.go
  constants.go
  detect.go
  detect_test.go
  go_logger.go
  init_test.go
  integration/buildpack_yaml_test.go
  integration/init_test.go
  run/main.go
Labels: semver:major

#372 Removes unneeded GoLogger
  build.go
  build_test.go
  go_logger.go
  run/main.go
Labels: semver:patch

#374 include-files: don't need to package go.mod/sum
  buildpack.toml
Labels: semver:patch

#375 Fail build when buildpack.yml detected
  detect.go
  detect_test.go
  init_test.go
  integration/environment_variable_configuration_test.go
Labels: semver:patch

#379 Adds Go 1.18 and removes Go 1.16
  buildpack.toml
  integration/default_test.go
  integration/environment_variable_configuration_test.go
  integration/layer_reuse_test.go
  integration/offline_test.go
Labels: semver:minor

#385 Remove built_at for more reproducible builds
  build.go
  build_test.go
  integration/layer_reuse_test.go
Labels: semver:patch
